version: '3.9'

services:
  db:
    image: postgres:14-alpine
    volumes:
      - ~/apps/users-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=bar
      - POSTGRES_USER=foo
      - POSTGRES_DB=db
    networks:
      - in
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - in

networks:
  in:
