server:
  port: 8080
spring:
  docker:
    compose:
      file: ./db-local/docker-compose.yml
  application:
    name: users-api
  datasource:
    url: jdbc:postgresql://localhost:5433/db?serverTimezone=UTC
    username: foo
    password: bar
    hikari:
      poolName: Hikari
      auto-commit: true
      maximum-pool-size: 2

application:
  allowed-origins:
    - http://localhost:80
    - http://localhost
    - http://localhost:4200
