version: '3.9'

services:
  db:
    image: postgres:14-alpine
    volumes:
      - ~/apps/users-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=bar
      - POSTGRES_USER=foo
      - POSTGRES_DB=db


